openapi: 3.0.1
info:
  title: GitHubAPI
  description: API Definition of GitHubAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/github
paths:
  /{user}:
    get:
      parameters:
      - name: user
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
